# Site settings
author: Sandile Keswa
title: Sandile Keswa | fullstack developer
email: me@sandile.io
description: Sandile Keswa's personal website and blog
keywords: sandile, keswa, web, development, software, programming, code, coding, rust, js, css, golang, blog, github, mobile, android
baseurl: ""
root: /
url: "http://www.sandile.io"
twitter_username: skeswa
github_username:  skeswa

# Build settings
markdown: kramdown
permalink: /:title
